(in-package #:cl-fly.api.ws-visitor)

(defun %payload-value (payload key)
  (or (getf payload key)
      (getf payload (intern (string-upcase key) :keyword))
      (and (hash-table-p payload) (gethash key payload nil))))

(defun %non-empty-string-p (value)
      (and (stringp value)
                   (> (length (string-trim '(#\Space #\Tab #\Return #\Newline) value)) 0)))

(defun %invalid-argument (message &optional client-msg-id)
      (let ((payload (list :code "INVALID_ARGUMENT" :message message)))
            (when (%non-empty-string-p client-msg-id)
                  (setf payload (append payload (list :clientMsgId client-msg-id))))
            (list :event "error" :payload payload)))

(defun %payload-prechat (payload)
      (let* ((nested (or (%payload-value payload :prechat)
                                                             (%payload-value payload "prechat")
                                                             (%payload-value payload :preChat)
                                                             (%payload-value payload "preChat")
                                                             (%payload-value payload :pre-chat)
                                                             (%payload-value payload "pre-chat")))
                         (source (if (listp nested) nested payload)))
            (list :issueType (or (%payload-value source :issueType)
                                                                         (%payload-value source "issueType")
                                                                         (%payload-value source :issue-type)
                                                                         (%payload-value source "issue-type"))
                              :urgency (or (%payload-value source :urgency)
                                                                   (%payload-value source "urgency")
                                                                   (%payload-value source :priority)
                                                                   (%payload-value source "priority"))
                              :language (or (%payload-value source :language)
                                                                        (%payload-value source "language")
                                                                        (%payload-value source :lang)
                                                                        (%payload-value source "lang"))
                              :customerTier (or (%payload-value source :customerTier)
                                                                                    (%payload-value source "customerTier")
                                                                                    (%payload-value source :customer-tier)
                                                                                    (%payload-value source "customer-tier"))
                              :intentScore (or (%payload-value source :intentScore)
                                                                               (%payload-value source "intentScore")
                                                                               (%payload-value source :intent-score)
                                                                               (%payload-value source "intent-score")))))

(defun handle-visitor-event (client-id event payload)
  (when (blacklisted-p "visitor" client-id)
    (return-from handle-visitor-event
      (list :event "error"
            :payload (list :code "BLACKLIST_BLOCKED"
                           :message "visitor blocked by blacklist"))))
  (register-client client-id :role "visitor")
  (touch-client client-id)
  (cond
    ((string= event "session.init")
     (let* ((session-id (or (%payload-value payload :sessionId)
                            (%payload-value payload "sessionId")
                            nil))
            (session (ensure-session session-id))
            (sid (getf session :session-id))
            (prechat (%payload-prechat payload))
            (updated (set-session-prechat sid
                                          :issue-type (getf prechat :issueType)
                                          :urgency (getf prechat :urgency)
                                          :language (getf prechat :language)
                                          :customer-tier (getf prechat :customerTier)
                                          :intent-score (getf prechat :intentScore))))
       (bind-client-session client-id (getf session :session-id))
       (touch-session-activity sid "visitor")
       (list :event "session.ready"
             :payload (list :sessionId sid
                            :status (session-status sid)
                            :welcomeMessage (getf session :welcome-message)
                            :intentScore (or (getf updated :intent-score) 0)
                            :prechat (list :issueType (or (getf updated :issue-type) "")
                                           :urgency (or (getf updated :urgency) "normal")
                                           :language (or (getf updated :language) "")
                                           :customerTier (or (getf updated :customer-tier) "standard"))))))
    ((string= event "message.send")
     (let* ((session-id (or (%payload-value payload :sessionId)
                            (%payload-value payload "sessionId")))
            (msg-type (or (%payload-value payload :messageType)
                          (%payload-value payload "messageType")
                          "text"))
            (content (or (%payload-value payload :content)
                         (%payload-value payload "content")
                         ""))
            (client-msg-id (or (%payload-value payload :clientMsgId)
                               (%payload-value payload "clientMsgId")
                               ""))
            (msg-type-lc (string-downcase (or msg-type ""))))
       (cond
         ((not (%non-empty-string-p session-id))
          (%invalid-argument "sessionId is required" client-msg-id))
         ((not (member msg-type-lc '("text" "image" "file") :test #'string=))
          (%invalid-argument "unsupported messageType" client-msg-id))
         (t
          (ensure-session session-id)
          (let ((saved (send-message session-id "visitor" msg-type-lc content :client-msg-id client-msg-id)))
            (touch-session-activity session-id "visitor")
            (set-session-typing session-id "visitor" "")
            (list :event "ack"
                  :payload (list :status "ok"
                                 :messageId (getf saved :message-id)
                                 :clientMsgId client-msg-id)))))))
    ((string= event "typing")
     (let* ((session-id (or (%payload-value payload :sessionId)
                            (%payload-value payload "sessionId")))
            (content (or (%payload-value payload :content)
                         (%payload-value payload "content")
                         "")))
       (if (not (%non-empty-string-p session-id))
           (%invalid-argument "sessionId is required")
           (progn
             (set-session-typing session-id "visitor" content)
             (list :event "ack" :payload (list :status "ok" :typing t))))))
    ((string= event "session.replay")
     (let* ((session-id (or (%payload-value payload :sessionId)
                            (%payload-value payload "sessionId")))
            (recent (and (%non-empty-string-p session-id)
                         (recent-messages session-id :limit 20)))
            (visible (and recent
                          (remove-if (lambda (item)
                                       (string= (string-downcase (or (getf item :message-type) "text"))
                                                "internal_note"))
                                     recent))))
       (if (not (%non-empty-string-p session-id))
           (%invalid-argument "sessionId is required")
           (list :event "session.replay"
                 :payload (list :sessionId session-id :messages visible)))))
    (t
     (list :event "error"
           :payload (list :code "UNSUPPORTED_EVENT"
                          :message "Unsupported visitor event")))))
